version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: quote-gen-container
    ports:
      - "5050:5050"
  web2:
    build: ./quote_disp
    container_name: quote-disp-container
    ports:
      - "5051:5051"
    depends_on:
      - web1